# Generated by Django 3.0.4 on 2020-04-13 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('F_name', models.CharField(max_length=55)),
                ('L_name', models.CharField(max_length=55)),
                ('mail', models.CharField(max_length=60)),
                ('gender', models.CharField(max_length=10)),
                ('city', models.CharField(max_length=30)),
                ('country', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=20)),
            ],
        ),
    ]
