# Generated by Django 3.0.4 on 2020-04-13 13:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_service'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service_provide',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=55)),
                ('address', models.CharField(max_length=55)),
                ('mobile_no', models.IntegerField()),
                ('experience', models.CharField(max_length=20)),
                ('charge', models.IntegerField()),
                ('charge_type', models.CharField(max_length=20)),
                ('aadhar_no', models.IntegerField()),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Service')),
            ],
        ),
    ]
